import Head from "next/head";
import Myappbar from "@/components/commons/Myappbar";
import { theme } from "@/styles/mui/theme";
import { ThemeProvider } from "@mui/material";
export default function Home() {
  return (
    <>
      <ThemeProvider theme={theme}>
      <Head>
        <title>Blog | the Movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Myappbar></Myappbar>
    <div>
      Blog
    </div>
    </ThemeProvider>
    </>
  );
}
