import Head from "next/head";
import Myappbar from "@/components/commons/Myappbar";
import { lighttheme ,darktheme} from "@/styles/mui/theme";
import { ThemeProvider } from "@mui/material";
import { useState } from "react";
import {CssBaseline} from "@mui/material";
import { useDispatch, useSelector } from "react-redux";
import { selectTheme } from "@/redux/reducers/themeReducer";
// import { useSelector } from "react-redux";
export default function Home() {
  const dispatch = useDispatch();
  const currentTheme = useSelector(selectTheme).activeTheme;
    // const [currentTheme,setCurrentTheme] = useState("light");
  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darktheme : lighttheme}>
      <CssBaseline></CssBaseline>
      <Head>
        <title>Blog | the Movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Myappbar />
    <div>
      Blog
    </div>
    </ThemeProvider>
    </>
  );
}
