import Head from "next/head";
//MUI imports
import Myappbar from "@/components/commons/Myappbar";
// import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
// import Toolbar from '@mui/material/Toolbar';
// import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
// import IconButton from '@mui/material/IconButton';
// import MenuIcon from '@mui/icons-material/Menu';
import { useState } from "react";
// import Link from "next/link";
import { theme } from "@/styles/mui/theme";
import { darktheme } from "@/styles/mui/theme";
import { ThemeProvider } from "@mui/material";
export default function Home() {
  const [visible , setVisible]= useState(false);
  


  const movies = [
   
   { name:"Avengers",
    img:"https://unsplash.com/photos/marvel-captain-america-figurine-TnXsLbvP2Qs",
    desc:"Directed by Mohanlal",
   },
   {
    name:"Iron man",
    img:"https://unsplash.com/photos/a-red-and-gold-toy-T844CLUxqvE",
    desc:"Directed by Shanty Xavier"
   },
   {
    name:"Groot",
    img:"https://unsplash.com/photos/a-small-baby-groote-sitting-on-a-log-in-the-woods-vMLFbB6dmZ0",
    desc:"Directed by Mammooty"
   }
  ]
  
  return (
    <>
      <ThemeProvider theme={darktheme}> 
      <Head>
        <title>The movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Box>
      
      <Myappbar></Myappbar>
    </Box>
    <Button onClick={()=> setVisible(!visible)}>Toggle </Button>
    <Box height="200px"/>
      { visible ? (
         <Box height="200px" width="200px"sx={{backgroundColor:"pink"}}/>
      ) : (
      <></>
      ) }
       {/* can be replaced with box */}
    </ThemeProvider>
    </>
  );
}
