import Head from "next/head";
//MUI imports
import Myappbar from "@/components/commons/Myappbar";
// import AppBar from '@mui/material/AppBar';
import Box from "@mui/material/Box";
// import Toolbar from '@mui/material/Toolbar';
// import Typography from '@mui/material/Typography';
import Button from "@mui/material/Button";
// import IconButton from '@mui/material/IconButton';
// import MenuIcon from '@mui/icons-material/Menu';
// import Link from "next/link";
import { lighttheme } from "@/styles/mui/theme";
import { darktheme } from "@/styles/mui/theme";
// import { ThemeProvider } from "@mui/material";
import { Container, CssBaseline, Grid, ThemeProvider } from '@mui/material';
// import customcard from "@/components/customcard";
import CustomCard from "@/components/customcard";

  // Redux
import { selectTheme } from "@/redux/reducers/themeReducer";
import { useDispatch } from "react-redux";
import { useSelector } from "react-redux";

  // import { selectTheme, getActiveTheme } from "@/redux/reducers/themeReducer";
export default function Home() {
  // const [visible, setVisible] = useState(false);
  // const [currentTheme,setCurrentTheme] = useState("light");


  const dispatch = useDispatch();
  const currentTheme = useSelector(selectTheme).activeTheme;
  const movies = [
    {
      name: "Avengers",
      img: "https://images.unsplash.com/photo-1561149877-84d268ba65b8?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      desc: "Directed by Mohanlal",
    },
    {
      name: "Iron man",
      img: "https://images.unsplash.com/photo-1657558045738-21507cf53606?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      desc: "Directed by Shanty Xavier",
    },
    {
      name: "Groot",
      img: "https://images.unsplash.com/photo-1636572481914-a07d36917486?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      desc: "Directed by Mammooty",
    },
  ];

  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darktheme : lighttheme}>
      <CssBaseline/>
        <Head>
          <title>The movie lovers club</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box>
          <Myappbar />
        </Box>
        {/* <Button onClick={() => setVisible(!visible)}>Toggle </Button>
        <Box  />
        {visible ? (
          <Box height="200px" width="200px" sx={{ backgroundColor: "pink" }} />
        ) : (
          <></>
        )} */}
        <Box >
         <Container>
          <Grid container spacing={2} direction="row" justifyContent="center" >
            
          {movies.map((movies) =>(
            <Grid size={3}>
            <CustomCard  name = {movies.name} image = {movies.img} description ={movies.desc} />
              
              </Grid>))
          }
          
          </Grid>
          </Container>
        </Box>
      </ThemeProvider>
    </>
  );

}
